[toolchain]
package_manager = "pnpm"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gold_rush = "FM7SQyRJExhzjFYvZ6XZTLkSSjNcMdDkCq89PWF9FtMB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/localnet/1.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/place-bet-single-round.spec.ts"
test_init = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize.spec.ts"
test_create_round = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/create-round.spec.ts"

[test]
startup_wait=50000
shutdown_wait=5000
upgradable=false

[test.validator]
bind_address="0.0.0.0"
url="http://api.mainnet-beta.solana.com"
ledger=".anchor/test-validator"
rpc_port=8899

[[test.validator.clone]]
address="2uPQGpm8X4ZkxMHxrAW1QuhXcse1AHEgPih6Xp9NuEWW"