[toolchain]
package_manager = "pnpm"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gold_rush = "FM7SQyRJExhzjFYvZ6XZTLkSSjNcMdDkCq89PWF9FtMB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/localnet/1.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/*.spec.ts"
test_init = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize.spec.ts"
test_create_round = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/create-round.spec.ts"
