[toolchain]
anchor_version = "0.31.1"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gold_rush = "3Ut8a8pvtNBEXY3ukuQzXgHpADByembaMqeCrBiyiKXv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/localnet/1.json"

[scripts]
deploy = "node migrations/deploy.js"
deploy_testing = "node migrations/deploy-testing.js"
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/emergency-unpause.spec.ts"

[test]
startup_wait = 50000
shutdown_wait = 5000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "http://api.mainnet-beta.solana.com"
ledger = ".anchor/test-validator"
rpc_port = 8899

[[test.validator.clone]]
address = "2uPQGpm8X4ZkxMHxrAW1QuhXcse1AHEgPih6Xp9NuEWW"
